#设置端口号为8888
server:
  port: 8888
  servlet:
    context-path: /api

#增加数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mi_bms?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: weirui
#redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0


#mybatis位置配置
mybatis:
  mapper-locations:  classpath:mapper/**/*.xml

# 日志配置
logging:
  config: classpath:logconfig/logback-spring.xml

